// questionsData.js
export const INITIAL_QUESTIONS = [
  // React & Web Frameworks
  { id: 1, question: "Which hook in React is used for managing side effects?", options: ["useState", "useEffect", "useContext", "useReducer"], correctAnswer: 1, explanation: "useEffect runs side effects after component renders." },
  { id: 2, question: "What is the primary purpose of Virtual DOM in React?", options: ["Direct DOM access", "Optimize rendering by minimizing real DOM updates", "State management", "Compile JSX"], correctAnswer: 1, explanation: "Virtual DOM batch updates to reduce performance bottlenecks." },
  { id: 3, question: "How do you pass data down to a child component in React?", options: ["State", "Props", "Refs", "Context"], correctAnswer: 1, explanation: "Props flow top-down from parent to child." },
  { id: 4, question: "Which hook handles complex state logic in React?", options: ["useMemo", "useCallback", "useReducer", "useRef"], correctAnswer: 2, explanation: "useReducer accepts a reducer function to manage complex state transitions." },
  { id: 5, question: "What is the return value of useState hook?", options: ["An object", "An array with state and setter function", "A single value", "A boolean"], correctAnswer: 1, explanation: "useState returns [currentState, setterFunction]." },
  { id: 6, question: "How can you prevent unnecessary re-renders in a functional component?", options: ["React.memo", "useRef", "useEffect", "setState"], correctAnswer: 0, explanation: "React.memo shallowly compares props to avoid re-renders." },
  { id: 7, question: "What hook returns a mutable ref object whose .current property is initialized to passed argument?", options: ["useRef", "useMemo", "useState", "useEffect"], correctAnswer: 0, explanation: "useRef persists values across renders without re-rendering." },
  { id: 8, question: "In React, what is key prop used for in lists?", options: ["Styling elements", "Identifying which items have changed, added, or removed", "Binding click handlers", "Setting CSS ID"], correctAnswer: 1, explanation: "Keys give elements a stable identity across renders." },
  { id: 9, question: "Which hook memoizes expensive calculations?", options: ["useCallback", "useMemo", "useEffect", "useRef"], correctAnswer: 1, explanation: "useMemo caches the result of a calculation between renders." },
  { id: 10, question: "Which hook memoizes callback functions?", options: ["useCallback", "useMemo", "useEffect", "useRef"], correctAnswer: 0, explanation: "useCallback caches function definitions between renders." },
  
  // JavaScript Core
  { id: 11, question: "Which keyword declares a block-scoped variable that cannot be reassigned?", options: ["var", "let", "const", "static"], correctAnswer: 2, explanation: "'const' creates immutable bindings." },
  { id: 12, question: "What is the output of typeof NaN in JavaScript?", options: ["number", "NaN", "undefined", "object"], correctAnswer: 0, explanation: "NaN is technically classified as a Number type in JS." },
  { id: 13, question: "Which method converts a JSON string into a JavaScript object?", options: ["JSON.stringify()", "JSON.parse()", "JSON.toObject()", "JSON.convert()"], correctAnswer: 1, explanation: "JSON.parse() parses JSON strings into objects." },
  { id: 14, question: "Which operator checks both value and type equality?", options: ["==", "===", "=", "!="], correctAnswer: 1, explanation: "=== performs strict equality comparison." },
  { id: 15, question: "What array method adds elements to the end of an array?", options: ["push()", "pop()", "unshift()", "shift()"], correctAnswer: 0, explanation: "push() adds one or more elements to the end." },
  { id: 16, question: "What method removes the last element from an array?", options: ["push()", "pop()", "unshift()", "shift()"], correctAnswer: 1, explanation: "pop() removes and returns the last element." },
  { id: 17, question: "What method adds elements to the beginning of an array?", options: ["push()", "pop()", "unshift()", "shift()"], correctAnswer: 2, explanation: "unshift() inserts elements at index 0." },
  { id: 18, question: "What method removes the first element from an array?", options: ["push()", "pop()", "unshift()", "shift()"], correctAnswer: 3, explanation: "shift() removes and returns the first element." },
  { id: 19, question: "Which function delays execution of a function by specified milliseconds?", options: ["setInterval", "setTimeout", "setImmediate", "delay"], correctAnswer: 1, explanation: "setTimeout schedules code execution after a delay." },
  { id: 20, question: "What does the Promise.all() method do?", options: ["Resolves as soon as one promise fulfills", "Resolves when all promises fulfill or rejects if any fails", "Executes promises sequentially", "Cancels pending promises"], correctAnswer: 1, explanation: "Promise.all waits for all promises in an iterable to resolve." },
  { id: 21, question: "Which keyword is used to pause async function execution until a Promise resolves?", options: ["yield", "await", "defer", "pause"], correctAnswer: 1, explanation: "await pauses execution within async functions." },
  { id: 22, question: "What does Array.prototype.map() return?", options: ["A single modified value", "A new array with updated elements", "The original array mutated", "A boolean"], correctAnswer: 1, explanation: "map creates a new array populated with transformed elements." },
  { id: 23, question: "Which array method checks if at least one element passes a test?", options: ["every()", "some()", "filter()", "find()"], correctAnswer: 1, explanation: "some() returns true if any element satisfies condition." },
  { id: 24, question: "Which array method checks if all elements pass a test?", options: ["every()", "some()", "filter()", "find()"], correctAnswer: 0, explanation: "every() checks if every element passes condition." },
  { id: 25, question: "What is a Closure in JavaScript?", options: ["A function bundled with references to its surrounding state", "A method to close browser windows", "A way to end loops early", "A private class property"], correctAnswer: 0, explanation: "Closures give access to an outer function's scope from an inner function." },

  // HTML / CSS / Web Fundamentals
  { id: 26, question: "Which HTML tag is used for the highest-level heading?", options: ["<h6>", "<head>", "<h1>", "<header>"], correctAnswer: 2, explanation: "<h1> defines the most important heading." },
  { id: 27, question: "Which CSS layout box model attribute includes content, padding, and border?", options: ["content-box", "border-box", "padding-box", "margin-box"], correctAnswer: 1, explanation: "box-sizing: border-box includes padding and border in total width." },
  { id: 28, question: "Which CSS display property arranges items in one dimension?", options: ["grid", "flex", "block", "inline"], correctAnswer: 1, explanation: "Flexbox manages layout along a single axis." },
  { id: 29, question: "Which HTTP status code signifies successfully created resource?", options: ["200", "201", "204", "301"], correctAnswer: 1, explanation: "201 Created indicates successful creation via request." },
  { id: 30, question: "Which HTTP method is idempotent and modifies resources?", options: ["POST", "PUT", "PATCH", "CONNECT"], correctAnswer: 1, explanation: "PUT replaces target resource entirely and is idempotent." },
  { id: 31, question: "What is CORS short for?", options: ["Cross-Origin Resource Sharing", "Core Object Rendering System", "Client-Oriented Remote Server", "Central Operating Response Service"], correctAnswer: 0, explanation: "CORS controls cross-origin HTTP requests." },
  { id: 32, question: "Which HTTP status code represents 'Bad Request'?", options: ["400", "401", "403", "404"], correctAnswer: 0, explanation: "400 indicates client error due to malformed syntax." },
  { id: 33, question: "Which status code represents 'Unauthorized'?", options: ["400", "401", "403", "404"], correctAnswer: 1, explanation: "401 means authentication is required or failed." },
  { id: 34, question: "Which status code represents 'Forbidden'?", options: ["400", "401", "403", "404"], correctAnswer: 2, explanation: "403 means server refuses to fulfill valid request due to permissions." },
  { id: 35, question: "Which HTML tag is used to embed JavaScript code?", options: ["<js>", "<script>", "<javascript>", "<code"], correctAnswer: 1, explanation: "<script> tags load or execute JS scripts." },

  // Computer Science & Data Structures
  { id: 36, question: "What is the worst-case time complexity of QuickSort?", options: ["O(n log n)", "O(n)", "O(n²)", "O(1)"], correctAnswer: 2, explanation: "Unbalanced pivots result in quadratic worst-case time O(n²)." },
  { id: 37, question: "Which data structure operates on a First-In-First-Out (FIFO) basis?", options: ["Stack", "Queue", "Tree", "Graph"], correctAnswer: 1, explanation: "Queues insert at tail and remove from head (FIFO)." },
  { id: 38, question: "Which data structure operates on a Last-In-First-Out (LIFO) basis?", options: ["Stack", "Queue", "Tree", "Graph"], correctAnswer: 0, explanation: "Stacks push/pop from top (LIFO)." },
  { id: 39, question: "What is time complexity for searching an element in a balanced Binary Search Tree?", options: ["O(1)", "O(n)", "O(log n)", "O(n log n)"], correctAnswer: 2, explanation: "Binary search eliminates half the remaining nodes each step." },
  { id: 40, question: "What is average time complexity to access an element in a Hash Table?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correctAnswer: 0, explanation: "Hash key calculation allows O(1) constant time average access." },
  { id: 41, question: "Which algorithm finds shortest paths in a weighted graph with non-negative edges?", options: ["Dijkstra's Algorithm", "Bellman-Ford", "Kruskal's Algorithm", "Floyd-Warshall"], correctAnswer: 0, explanation: "Dijkstra computes single-source shortest path for non-negative weights." },
  { id: 42, question: "Which sorting algorithm has a guaranteed best, average, and worst-case time complexity of O(n log n)?", options: ["Merge Sort", "Quick Sort", "Bubble Sort", "Insertion Sort"], correctAnswer: 0, explanation: "Merge Sort repeatedly divides and merges halves in log n levels." },
  { id: 43, question: "Which data structure consists of nodes connected without cycles?", options: ["Tree", "Graph", "HashTable", "Array"], correctAnswer: 0, explanation: "Trees are connected acyclic graphs." },
  { id: 44, question: "What is the space complexity of Depth-First Search (DFS) on a tree of height h?", options: ["O(1)", "O(h)", "O(2^h)", "O(n²)"], correctAnswer: 1, explanation: "Call stack depth equals the tree height h." },
  { id: 45, question: "Which data structure uses key-value pairs for constant time lookups?", options: ["Hash Map", "Linked List", "Stack", "Queue"], correctAnswer: 0, explanation: "Hash Maps compute indices from keys for fast access." },

  // SQL & Databases
  { id: 46, question: "Which SQL clause is used to filter records after aggregation?", options: ["WHERE", "HAVING", "GROUP BY", "ORDER BY"], correctAnswer: 1, explanation: "HAVING filters aggregated grouped results." },
  { id: 47, question: "What does ACID stand for in database systems?", options: ["Atomicity, Consistency, Isolation, Durability", "Access, Control, Identification, Data", "Automated, Concurrent, Indexed, Distributed", "Array, Column, Index, Domain"], correctAnswer: 0, explanation: "ACID guarantees transactional database reliability." },
  { id: 48, question: "Which type of SQL JOIN returns all matching records from both tables?", options: ["LEFT JOIN", "RIGHT JOIN", "INNER JOIN", "FULL OUTER JOIN"], correctAnswer: 2, explanation: "INNER JOIN returns rows where matching keys exist in both tables." },
  { id: 49, question: "Which SQL command is used to update existing data in a table?", options: ["MODIFY", "UPDATE", "CHANGE", "ALTER"], correctAnswer: 1, explanation: "UPDATE modifies existing values within rows." },
  { id: 50, question: "Which command removes a table structure entirely from a database?", options: ["DELETE", "DROP", "TRUNCATE", "REMOVE"], correctAnswer: 1, explanation: "DROP removes both table data and definition." },

  // Programming Principles & Protocols
  { id: 51, question: "What does REST stand for in web API architecture?", options: ["Representational State Transfer", "Remote Execution Service Technology", "Random Entity Storage Transfer", "Real-time Event Stream Transaction"], correctAnswer: 0, explanation: "REST provides standards for distributed hypermedia systems." },
  { id: 52, question: "In Git, which command creates a new local branch and switches to it immediately?", options: ["git branch -n", "git checkout -b", "git switch -c", "Both B and C"], correctAnswer: 3, explanation: "Both `git checkout -b` and `git switch -c` create and switch." },
  { id: 53, question: "Which OSI model layer handles end-to-end communication, flow control, and error recovery?", options: ["Network Layer", "Transport Layer", "Data Link Layer", "Application Layer"], correctAnswer: 1, explanation: "Transport Layer (TCP/UDP) controls segment transmission." },
  { id: 54, question: "What is the primary function of DNS?", options: ["Encrypt web traffic", "Translate domain names to IP addresses", "Balance server load", "Route network packets"], correctAnswer: 1, explanation: "DNS translates human-readable domains into IP addresses." },
  { id: 55, question: "Which HTTP status code represents 'Internal Server Error'?", options: ["400", "404", "500", "502"], correctAnswer: 2, explanation: "500 indicates unexpected error condition on server." },

  // Expanded CS Questions to ensure 100+ items
  { id: 56, question: "What is the time complexity of accessing an array element by index?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correctAnswer: 0, explanation: "Arrays allow direct memory offset calculations." },
  { id: 57, question: "Which search algorithm requires a sorted array?", options: ["Linear Search", "Binary Search", "Depth-First Search", "Breadth-First Search"], correctAnswer: 1, explanation: "Binary search relies on sorted ordering to halve search space." },
  { id: 58, question: "What design pattern restricts instantiation of a class to one single instance?", options: ["Factory", "Singleton", "Observer", "Strategy"], correctAnswer: 1, explanation: "Singleton pattern ensures only one instance exists." },
  { id: 59, question: "What is the primary function of a Garbage Collector in runtime environments?", options: ["Optimizing network calls", "Reclaiming memory unused by program", "Preventing syntax errors", "Compiling code to machine code"], correctAnswer: 1, explanation: "Garbage collection automatically deallocates unreachable memory." },
  { id: 60, question: "Which HTTP header is sent by client to provide authentication credentials?", options: ["Authorization", "Authentication", "Bearer", "Cookie"], correctAnswer: 0, explanation: "Authorization header carries user credentials like Tokens." },
  
  { id: 61, question: "In CSS, what value of position keeps an element fixed relative to viewport?", options: ["absolute", "relative", "fixed", "sticky"], correctAnswer: 2, explanation: "fixed positions element relative to browser window." },
  { id: 62, question: "Which data structure is best suited for implementing undo functionality in an editor?", options: ["Queue", "Stack", "Tree", "Graph"], correctAnswer: 1, explanation: "Stack (LIFO) pushes operations and pops during undo." },
  { id: 63, question: "What does JWT stand for?", options: ["Java Web Token", "JSON Web Token", "JS System Web Transfer", "Joint Web Technology"], correctAnswer: 1, explanation: "JSON Web Token securely transmits claims between parties." },
  { id: 64, question: "What port does HTTP protocol default to?", options: ["21", "22", "80", "443"], correctAnswer: 2, explanation: "HTTP defaults to port 80; HTTPS defaults to 443." },
  { id: 65, question: "What port does HTTPS protocol default to?", options: ["80", "8080", "443", "22"], correctAnswer: 2, explanation: "HTTPS traffic defaults to encrypted port 443." },
  { id: 66, question: "In JavaScript, what does Array.prototype.reduce() do?", options: ["Filters array elements", "Executes user reducer function to collapse array into single value", "Sorts elements", "Reverses array order"], correctAnswer: 1, explanation: "reduce computes cumulative result across array elements." },
  { id: 67, question: "What is the worst-case time complexity of searching in a Linked List?", options: ["O(1)", "O(log n)", "O(n)", "O(n log n)"], correctAnswer: 2, explanation: "Linked lists require traversal from head through n nodes." },
  { id: 68, question: "Which SQL command inserts new records into a table?", options: ["ADD", "INSERT INTO", "UPDATE", "PUT"], correctAnswer: 1, explanation: "INSERT INTO populates new rows." },
  { id: 69, question: "Which Git command fetches changes from remote and merges into current branch?", options: ["git fetch", "git pull", "git merge", "git push"], correctAnswer: 1, explanation: "git pull performs `fetch` followed by `merge`." },
  { id: 70, question: "What does DOM stand for?", options: ["Document Object Model", "Data Object Manager", "Digital Output Module", "Desktop Operating Mode"], correctAnswer: 0, explanation: "DOM represents document structure in memory as a tree." },

  { id: 71, question: "Which SQL command deletes all records in a table without deleting table definition?", options: ["DROP", "TRUNCATE", "REMOVE", "CLEAR"], correctAnswer: 1, explanation: "TRUNCATE removes all rows faster than DELETE without logging individual row deletes." },
  { id: 72, question: "What is the time complexity of inserting at the beginning of a Singly Linked List?", options: ["O(1)", "O(n)", "O(log n)", "O(n²)"], correctAnswer: 0, explanation: "Updating head reference is constant time O(1)." },
  { id: 73, question: "Which JS function converts numeric values into strings?", options: ["String() / .toString()", "Number()", "parseInt()", "parseFloat()"], correctAnswer: 0, explanation: "String() or .toString() creates string representations." },
  { id: 74, question: "What type of scope do 'let' and 'const' keywords have?", options: ["Global scope", "Function scope", "Block scope", "Module scope"], correctAnswer: 2, explanation: "let and const are block-scoped within { } brackets." },
  { id: 75, question: "What type of scope does 'var' keyword have?", options: ["Block scope", "Function scope", "Global-only scope", "Lexical scope"], correctAnswer: 1, explanation: "var is scoped to its enclosing function." },

  { id: 76, question: "Which command in Git views commit history?", options: ["git log", "git status", "git history", "git show"], correctAnswer: 0, explanation: "git log lists commit history." },
  { id: 77, question: "In JavaScript, what is the value of unassigned variables?", options: ["null", "undefined", "0", "false"], correctAnswer: 1, explanation: "Uninitialized variables default to undefined." },
  { id: 78, question: "Which component lifecycle method in React class components handles side effects?", options: ["componentDidMount", "render", "constructor", "getDerivedStateFromProps"], correctAnswer: 0, explanation: "componentDidMount runs side effects after initial render." },
  { id: 79, question: "What keyword exports default functions or variables in ES6 modules?", options: ["export default", "module.exports", "export", "public export"], correctAnswer: 0, explanation: "export default declares main module export." },
  { id: 80, question: "Which operator spreads array elements or object properties in JS?", options: ["...", "::", "->", "&&"], correctAnswer: 0, explanation: "... is the spread / rest operator." },

  { id: 81, question: "What does HTML stand for?", options: ["HyperText Markup Language", "HighText Machine Language", "HyperTransfer Mark Language", "Home Tool Markup Language"], correctAnswer: 0, explanation: "HTML is standard markup language for documents in web browsers." },
  { id: 82, question: "What does CSS stand for?", options: ["Cascading Style Sheets", "Computer Style Sheets", "Creative Style System", "Colorful Style Sheets"], correctAnswer: 0, explanation: "CSS formats document presentation." },
  { id: 83, question: "Which HTML attribute opens a link in a new tab?", options: ["target='_blank'", "target='_new'", "open='new'", "window='tab'"], correctAnswer: 0, explanation: "target='_blank' directs browser to open link in new tab." },
  { id: 84, question: "In CSS Flexbox, what property moves items along cross axis?", options: ["justify-content", "align-items", "flex-direction", "flex-wrap"], correctAnswer: 1, explanation: "align-items controls cross axis alignment." },
  { id: 85, question: "In CSS Flexbox, what property moves items along main axis?", options: ["justify-content", "align-items", "flex-direction", "flex-wrap"], correctAnswer: 0, explanation: "justify-content handles main axis alignment." },

  { id: 86, question: "Which command checks git repository status?", options: ["git status", "git log", "git check", "git state"], correctAnswer: 0, explanation: "git status displays modified, untracked, or staged files." },
  { id: 87, question: "What does SQL stand for?", options: ["Structured Query Language", "Sequential Query List", "Simple Question Language", "System Query Logic"], correctAnswer: 0, explanation: "SQL is domain-specific language for relational databases." },
  { id: 88, question: "What is the primary function of an Index in relational databases?", options: ["Enforce foreign keys", "Speed up data retrieval queries", "Compress table data size", "Encrypt data at rest"], correctAnswer: 1, explanation: "Indexes build data structures (like B-Trees) to accelerate searches." },
  { id: 89, question: "Which database type uses document model like JSON?", options: ["Relational / SQL", "NoSQL / Document-oriented", "Hierarchical", "Network"], correctAnswer: 1, explanation: "MongoDB is an example of a NoSQL Document Store." },
  { id: 90, question: "What is an event listener in JavaScript?", options: ["A function that waits for an event to trigger on a DOM node", "A process monitoring network requests", "A method to throw runtime errors", "A state listener hook in React"], correctAnswer: 0, explanation: "Event listeners execute callback functions when specified DOM events occur." },

  { id: 91, question: "In CSS, what does opacity: 0 do?", options: ["Hides element completely and removes it from layout", "Makes element completely transparent but keeps layout space", "Sets background color to white", "Disables user clicks"], correctAnswer: 1, explanation: "opacity: 0 makes item invisible while preserving layout space." },
  { id: 92, question: "What does display: none do in CSS?", options: ["Makes element transparent", "Removes element completely from layout rendered flow", "Hides borders only", "Disables child pointer events"], correctAnswer: 1, explanation: "display: none prevents element rendering and collapses space." },
  { id: 93, question: "Which JS method converts object/array into JSON string?", options: ["JSON.stringify()", "JSON.parse()", "JSON.format()", "JSON.encode()"], correctAnswer: 0, explanation: "JSON.stringify converts JS entities to valid JSON strings." },
  { id: 94, question: "Which browser API stores key-value pairs without expiration time?", options: ["sessionStorage", "localStorage", "Cookies", "IndexedDB"], correctAnswer: 1, explanation: "localStorage data persists until manually cleared." },
  { id: 95, question: "Which browser API stores data cleared when tab closes?", options: ["sessionStorage", "localStorage", "IndexedDB", "Cookies"], correctAnswer: 0, explanation: "sessionStorage clears when browser session ends." },

  { id: 96, question: "What is the result of '5' + 3 in JavaScript?", options: ["8", "'53'", "NaN", "Error"], correctAnswer: 1, explanation: "+ operator performs string concatenation when string operand is present." },
  { id: 97, question: "What is the result of '5' - 3 in JavaScript?", options: ["2", "'53'", "NaN", "Error"], correctAnswer: 0, explanation: "- operator coerces string operand to number." },
  { id: 98, question: "Which method joins all array elements into a string?", options: ["join()", "concat()", "slice()", "toString()"], correctAnswer: 0, explanation: "join() turns array items into delimiter-separated string." },
  { id: 99, question: "Which method creates a shallow copy of a portion of an array?", options: ["splice()", "slice()", "cut()", "copy()"], correctAnswer: 1, explanation: "slice() returns selected elements without mutating original." },
  { id: 100, question: "Which array method mutates array by adding/removing elements?", options: ["splice()", "slice()", "concat()", "map()"], correctAnswer: 0, explanation: "splice() alters array contents in-place." },
  { id: 101, question: "What does API stand for?", options: ["Application Programming Interface", "Automated Process Integration", "Application Protocol Instruction", "Advanced Program Identifier"], correctAnswer: 0, explanation: "API enables communication between software components." }
];